include ../doctest_main/
include ../../../libcornet/
#import libs  = cpu_utils%lib{cpu_utils}
import libs = doctest%lib{doctest}

#testscript{**}
./: exe{crypto_test}: {cxx}{crypto_test} $libs ../../../libcornet/lib{cornet} ../doctest_main/lib{doctest_main} 
./: exe{tls_ciphers_test}: {cxx}{tls_ciphers_test} $libs ../../../libcornet/lib{cornet} ../doctest_main/lib{doctest_main} 
