import libs = libcornet%lib{cornet}
import libs += pioneer19_utils%lib{pioneer19_utils}
#import libs += libhello%lib{hello}

#include ../libcornet/
exe{echo_client}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$src_root/.."
#cxx.poptions =+ "-I$out_root" "-I$src_root"
