int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
#import imp_libs += libhello%lib{hello}
import imp_libs += pioneer19_utils%lib{pioneer19_utils}

lib{cornet}: {hxx ixx txx cxx}{** -version} hxx{version} $imp_libs $int_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
hxx{version}: dist  = true
hxx{version}: clean = ($src_root != $out_root)

cxx.poptions =+ "-I$out_root" "-I$src_root"

bin.lib = static

lib{cornet}:
{
    bin.lib = static
}

obja{*}: cxx.poptions += -DLIBCORNET_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBCORNET_SHARED_BUILD

lib{cornet}: cxx.export.poptions = "-I$out_root" "-I$src_root"

liba{cornet}: cxx.export.poptions += -DLIBCORNET_STATIC
libs{cornet}: cxx.export.poptions += -DLIBCORNET_SHARED

lib{cornet}: cxx.export.libs = $int_libs

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{cornet}: bin.lib.version = @"-$version.project_id"
else
  lib{cornet}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the libcornet/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}: install         = include/libcornet/
{hxx ixx txx}{*}: install.subdirs = true
